package com.example.RAG.Controller;

import com.example.RAG.Service.RagQueryService;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RequestMapping("/api/rag")
public class RagController {

    private final RagQueryService ragQueryService;

    // Spring will automatically inject the RagQueryService bean
    // that you defined in your IngestionConfig.
    public RagController(RagQueryService ragQueryService) {
        this.ragQueryService = ragQueryService;
    }

    /**
     * Endpoint to ask a question to the RAG system.
     * Example URL: GET http://localhost:8080/api/rag/query?question=What is the main feature of product X?
     * * @param question The user's query string.
     * @return The response generated by the LLM (augmented by the RAG context).
     */
    @GetMapping("/query")
    public ResponseEntity<String> queryRAG(@RequestParam String question) {
        if (question == null || question.trim().isEmpty()) {
            return ResponseEntity.badRequest().body("Please provide a 'question' parameter.");
        }

        // 1. Calls the RagQueryService
        // 2. The service uses QuestionAnswerAdvisor to find relevant context from the VectorStore
        // 3. The service sends the augmented prompt to the LLM (ChatClient)
        // 4. Returns the LLM's final response
        String answer = ragQueryService.query(question);

        return ResponseEntity.ok(answer);
    }
}